### ISSUE TITLE
Flushing behaviour

### ISSUE THREAD

**Issue by dalcde** [psychon/x11rb#101]
It appears that `x11rb` requires the user the explicitly flush after making requests such as `change_window_attributes`, which was not necessary with `xcb`. If this is intended, this should be more clearly documented.

**Comment by psychon** [comment]
Uhm. What exactly do you mean? The part "which was not necessary with xcb" is wrong, I think.

Flush on `XCBConnection` just calls `xcb_flush()` and so is equivalent to when it is necessary to flush in xcb:
https://github.com/psychon/x11rb/blob/d40f94040028706bf17ff744f5e36ba9dacb6db4/src/xcb_ffi.rs#L258-L263

Flush on `RustConnection` does not do anything (since so far there is no buffering, everything is written immediately), so this function is never necessary to call:
https://github.com/psychon/x11rb/blob/d40f94040028706bf17ff744f5e36ba9dacb6db4/src/rust_connection.rs#L283-L285

The general approach of libxcb is:
- There is an output buffer.
- When you write a request that is larger than the remaining free space in the output buffer, everything (the contents and the output buffer and your new request) are written at once.
- When you wait for a reply (`xcb_wait_for_reply()` / `xcb_wait_for_reply64()` in libxcb, these are called by functions like `xcb_get_input_focus_reply()` which in turn is what the user of libxcb calls; in x11rb this is the `reply()` function on the cookie) and the request in question was not sent yet, it will be sent.
- Some more internal stuff (buffer for sending FDs is full; I doubt this ever happens in practice, `xcb_take_socket()`)
- Nothing else

The ChangeWindowAttributes request does not have a reply, thus it ends up in the output buffer and is sent whenever anything else requires a flush. The behaviour here should be the same between libxcb and x11rb.

(Note that something like `xcb_change_window_attributes()` then `xcb_get_input_focus_reply(xcb_get_input_focus())` flushes the buffer for the GetInputFocus request, which means that the ChangeWindowAttributes request is also sent, because it is already in the output buffer.)

**Comment by dalcde** [comment]
Ah I see. I've been using the checked version in the past so it automatically flushed for me.

**Comment by psychon** [comment]
Oh, right. For the sake of people finding this via Google:

Checked requests are remembered internally when sent. This prevents the errors from being returned by things like `xcb_wait_for_event()`. Besides that, there is nothing special about checked requests on the sending side.

When checking a checked request, xcb checks if there was any later request with a reply. If not, a `GetInputFocus` is sent and its reply is discarded. Then, the output buffer is flushed and when the reply to the later request comes, xcb can be sure that there will be no error in response to the checked request (and of course: if an error comes, xcb can be sure that there was an error).

I'll close this issue. I think everything was addressed.
