### ISSUE TITLE
impl From<&GenericEvent> for ...Event

### ISSUE THREAD

**Issue by dalcde** [psychon/x11rb#106]
There should be a convenient method to turn a `&GenericEvent` into a concrete instance of an event. Currently, it can be done by, e.g.
```rust
let e : ExposeEvent = ExposeEvent::try_from(event.raw_bytes())?;
```

**Comment by psychon** [comment]
Why do you want `From<&GenericEvent>`, specifically the borrow `&`?
(Note to self: This is actually a good idea and should be implemented - events are (most of the time) just 32 bytes, and parsing copies stuff anyway.)

Currently, there is `From<GenericEvent>` already implemented (but this appears as `From<X11GenericEvent>` in the API docs because I had a problem with a name collision and had to `use x11_utils::GenericEvent as X11GenericEvent` as a cheap work-around that I am not happy about).

Example from the examples (where `event` is a `GenericEvent`):
https://github.com/psychon/x11rb/blob/79a2657ab07f0ea18fe23989ceb01185c34e5861/examples/xeyes.rs#L269

**Comment by psychon** [comment]
Thanks for the suggestion. My question for the `why` above was specifically meant as: So far, I have not come into a situation where I needed to keep the original `GenericEvent` and also have a parsed version of the actual event, so the owned `From` was enough for me.

**Comment by dalcde** [comment]
In my case, I have several objects that share the connnection, and I
want to be able to pass the event to all of the objects' event handlers
to process. I can parse it beforehand but that will require every object
to have a handler for every event, which is not very convenient.

**Comment by psychon** [comment]
Ah, yeah, that's a very good reason. Especially since "parsing" should be quite cheap and quick.

In the beginning I was thinking about adding some `enum` that wraps "all the events", but extensions also have events and the enum would be the only thing (so far) that "crosses between" extensions. And also, it would be huge (there are 113 events defined in all the XML files together).

>  but that will require every object to have a handler for every event, which is not very convenient.

You could have a trait for "something that can react to events" and the trait could provide empty default implementations for all the methods.
