### ISSUE TITLE
link to crates.io, docs.rs etc in readme.

### ISSUE THREAD

**Issue by phiresky** [psychon/x11rb#161]

**Comment by psychon** [comment]
Do you happen to have a list for "etc"?

I just went to https://crates.io/. The "most downloaded" crate is rand, so time to look at randr's README:
```
[![Build Status](https://travis-ci.org/rust-random/rand.svg?branch=master)](https://travis-ci.org/rust-random/rand)
[![Build Status](https://ci.appveyor.com/api/projects/status/github/rust-random/rand?svg=true)](https://ci.appveyor.com/project/rust-random/rand)
[![Crate](https://img.shields.io/crates/v/rand.svg)](https://crates.io/crates/rand)
[![Book](https://img.shields.io/badge/book-master-yellow.svg)](https://rust-random.github.io/book/)
[![API](https://img.shields.io/badge/api-master-yellow.svg)](https://rust-random.github.io/rand)
[![API](https://docs.rs/rand/badge.svg)](https://docs.rs/rand)
[![Minimum rustc version](https://img.shields.io/badge/rustc-1.32+-lightgray.svg)](https://github.com/rust-random/rand#rust-version-requirements)
```
I'm not too keen on the build status since it seems not too useful to me. Or is this just a way of saying "oh, we use CI!" and the actual build status is not important? Well, okay.

Since I haven't written a book... well, what do you think about the following? Is this what you had in mind?

[![Build Status](https://travis-ci.org/psychon/x11rb.svg?branch=master)](https://travis-ci.org/psychon/x11rb) [![Crate](https://img.shields.io/crates/v/x11rb.svg)](https://crates.io/crates/x11rb) [![API](https://docs.rs/x11rb/badge.svg)](https://docs.rs/x11rb) ![Minimum rustc version](https://img.shields.io/badge/rustc-1.37+-lightgray.svg)

(No idea where the "minimum rustc version" should link to, so I just removed the link)

**Comment by phiresky** [comment]
Yeah what you're saying sounds good. My request personally was really just crates.io and docs.rs. Without the first it's not even clear what the name of the crate is (many crates have stuff like rs suffix or not and the repo name is not the same as the crate name) and whether or not it is on crates.io or not. I first thought this was just an experiment and not actually published on crates.io until i manually typed crates.io/crates/x11rb as an url.

The docs link is useful  because some crates host their documentations on github or something or don't have any real generated documentation (just types but no docstrings). I personally don't care about other stuff, but something like whether it works on stable (basically the rust version you have in your example) or similar might be useful I guess.

**Comment by psychon** [comment]
Okay, thanks for opening an issue about this. Feel free to do so with any questions you might have.

> The docs link is useful because some crates [...] don't have any real generated documentation (just types but no docstrings).

Beware of the `x11rb::generated` module. :yum:
 In case you did not notice yet: This repo uses the same XML description that is also used for generating the C code in libxcb. Sadly, not much of documentation is available in the XML and the docs that are available assumes that they end up in XCB, so contains C code.
