### ISSUE TITLE
Consider using rustfmt

### ISSUE THREAD

**Issue by eduardosm** [psychon/x11rb#226]
I don't know if you are aware of it, Rust provides [rustfmt](https://github.com/rust-lang/rustfmt), a tool for automatic code formatting.

You might want to consider using it, but it's a matter of personal opinion, so feel free to close this issue.

**Comment by psychon** [comment]
Well... I already took a look at it: https://github.com/psychon/x11rb/tree/rustfmt

My problem is in the way that I install Rust. I am from the "do not pipe the output of curl into a shell, even if the web page tells you it is safe"-camp. I installed Rust via `apt-get install rustc cargo`. This is also how the minimal supported Rust version of this crate came to be: It was whatever was in Debian testing when I started this.

Rustfmt and clippy are both not packaged in Debian. For clippy, this is not soooo bad, because Travis tells me (after five minutes...) what stuff I should do different. I can then fix my code. The same workflow for rustfmt cannot really work. Fishing `rustfmt` format changes out of a Travis build log is not going to fly.

So, my problem with `rustfmt` boils down to a problem of "how to install stuff". I doubt that we can find a workable solution here. While running stuff through `rustfmt` once and sending it as a pull request can work once, it is not really workable long-term.

(And if I were to use `rustfmt`, I guess I would not configure it, but instead "go with the defaults". I am only a bit difficult to work with, not completely difficult. ;-) )

(How come you open this issue? I know that my code format is at times... uhm... improvable.... but is it *this* bad? :-) )

**Comment by eduardosm** [comment]
> My problem is in the way that I install Rust. I am from the "do not pipe the output of curl into a shell, even if the web page tells you it is safe"-camp. I installed Rust via `apt-get install rustc cargo`. This is also how the minimal supported Rust version of this crate came to be: It was whatever was in Debian testing when I started this.

I believe you mean the official process of installing rustup (https://rustup.rs/). In my case, I installed rustup from the Manjaro repositories. What about downloading the shell script, taking a look and running it?

> (How come you open this issue? I know that my code format is at times... uhm... improvable.... but is it _this_ bad? :-) )

Well... the formatting can be improved a bit, and a formatter also helps to keep a consistent style while getting rid of invisible typos such as leading whitespaces or tabs instead of spaces.

Formatting the code will likely cause merge conflicts, so, if formatter is ever going to be run on this project, it should be done now, before it starts getting more pull requests.

**Comment by dalcde** [comment]
For me, the main benefit of using `rustfmt` is that I can write poorly formatted code and then let `rustfmt` take care of the formatting, which saves quite a bit of work.

**Comment by psychon** [comment]
> What about downloading the shell script, taking a look and running it?

<details>
Well, okay. So this script downloads https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init and runs the result. I am surprised that I did not get the URL wrong. The resulting file is 12 MiB large and:
```
$ file rustup-init 
rustup-init: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.9, with debug_info, not stripped
```
(Off topic: After `strip`, the file only has 9.6 MiB)

So, this is now a random bunch of code that I cannot look at and do not really know what it does.
</details>

The problem for me is not really "download a shell script and run it", but "download something executable and run it". At work, on one hand we are told to not click links from random e-mails, and on the other hand people execute random binaries from the internet and hope for the best. That scares me.

So, sorry, but I do not think this can be made to work with me currently.

> before it starts getting more pull requests.

Yay for more PRs. :-)

**Comment by eduardosm** [comment]
> So, this is now a random bunch of code that I cannot look at and do not really know what it does.

Doesn't this apply also for packages installed with `apt-get`?

**Comment by psychon** [comment]
For Debian packages, I know a bit about the process that produced them and that they are cryptographically verified in lots of ways that makes it very unlikely that someone is giving me a malicious binary. (The whole Release file is signed by the archive signing key and contains the hash sums of files that would be installed.) With rustup, TLS is all the protection that I get and (as far as I can see) no binary signatures are involved.

**Comment by eduardosm** [comment]
Would you still accept a PR to do bulk formatting of the current code?

**Comment by psychon** [comment]
Yup. I would even try to change my own coding style to make it look more like `rustfmt`. I just do not know where my style is "wrong".

Again, sorry for making this so difficult and thank you both for all your contributions.

**Comment by psychon** [comment]
Complicated work-around: Use a chroot or a VM for `rustfmt`.
