### ISSUE TITLE
GetModifierMappingReply is missing the field `keycodes_per_modifier`

### ISSUE THREAD

**Issue by exit91** [psychon/x11rb#411]
The attribute `keycodes_per_modifier` is parsed here: 

https://github.com/psychon/x11rb/blob/e9dab004d422297dea2262905e28baca27730efc/src/protocol/xproto.rs#L17646-L17652

However, it is ultimately missing in the definition of `GetModifierMappingReply`.

https://github.com/psychon/x11rb/blob/e9dab004d422297dea2262905e28baca27730efc/src/protocol/xproto.rs#L17639-L17645

According to the [C library](https://xcb.freedesktop.org/manual/structxcb__get__modifier__mapping__reply__t.html) the field should exist.
Also compare that with the [xcb proto file](https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/blob/master/src/xproto.xml#L5600).

Even *if* the assumption `keycodes_per_modifier * 8 = length of the keycode vector` holds everywhere (thereby making the field obsolete), shouldn't this be documented?

Should this turn out to be a flaw in the code generator I'd encourage you to have a look at functions like `set_modifier_mapping` as well, which would similarly lack a `keycodes_per_modifier` parameter.

https://github.com/psychon/x11rb/blob/e9dab004d422297dea2262905e28baca27730efc/src/protocol/xproto.rs#L17570

**Comment by psychon** [comment]
Hi,

thanks for opening this issue. I am writing these lines after I have written the rest of the following text. I felt that the following sounds a bit negative and so I wanted to emphasise: Thanks for opening this issue and feel free to make suggestions. I am trying so explain why things are the way they are and would be very happy if you tell us how to improve.

> According to the C library the field should exist.

Well... random API example from libxcb:
```C
xcb_set_pointer_mapping_cookie_t
xcb_set_pointer_mapping_unchecked (xcb_connection_t *c,
                                   uint8_t           map_len,
                                   const uint8_t    *map);
```
The same thing in x11rb:
https://github.com/psychon/x11rb/blob/e9dab004d422297dea2262905e28baca27730efc/src/protocol/xproto.rs#L17393
The `map_len` argument disappeared. Instead, the code uses the length of the provided slice:
https://github.com/psychon/x11rb/blob/e9dab004d422297dea2262905e28baca27730efc/src/protocol/xproto.rs#L17398
The same mechanism triggered here. The `keycodes_per_modifier` field is interpreted as the length field of the following list and then inferred from other information. The relevant XML (which I bet you already saw):
https://github.com/psychon/x11rb/blob/e9dab004d422297dea2262905e28baca27730efc/xcb-proto-1.14-1-g2b3559c/src/xproto.xml#L5602-L5609

This XML says that the length of the list is always 8 times of `keycodes_per_modifier`. With libxcb, this gives you the length of the list so that you can avoid out-of-bounds access. With x11rb, the `Vec` already basically provides this kind of thing.

This is especially important for requests were the API caller would have to provide the length of the slice and the actual slice. If both the slice and its length were part of the API, what should happen if some inconsistent values are provided? Return an error to the caller? panic? I think making it impossible to provide inconsistent values is a lot nicer.

At the point where this struct is generated, we do not really know if the information comes from the X11 server or the API user (or both - some structs can be part of requests and replies), so cannot really tell apart the fields here.

> Even if the assumption keycodes_per_modifier * 8 = length of the keycode vector holds everywhere (thereby making the field obsolete), shouldn't this be documented?

How would you suggest that we document this? Adding a comment to the doc of each struct containing a field that was removed?

(I am not trying to make fun of you here, I am honestly asking for ways that things could be improved.)

Random patch to show the scope of this: The following change to the code generator
```diff
diff --git a/generator/src/generator/namespace.rs b/generator/src/generator/namespace.rs
index b166bbe..4dd88d0 100644
--- a/generator/src/generator/namespace.rs
+++ b/generator/src/generator/namespace.rs
@@ -1836,6 +1836,11 @@ impl<'ns, 'c> NamespaceGenerator<'ns, 'c> {
                         field_type
                     );
                 }
+            } else {
+                match field {
+                    xcbdefs::FieldDef::Pad(_) => {}, // ignore
+                    field => outln!(out.indent(), "// deducible: {:?}", field.name()),
+                }
             }
         }
         outln!(out, "}}");
```
leads to a change with this diffstat:   22 files changed, 290 insertions(+)
The full diff is here showing all the fields that are left out: https://gist.github.com/psychon/fa5d1880cacb1d715df5cccd1fc3a053
(My point here is "there are lots of fields like this")

Hm... Random idea at the end: How about generating accessors? Something like the following (which would be part of `impl GetModifierMappingReply`). Would that do what you wanted?
```rust
/// Provide the value of the `keycodes_per_modifer` field.
///
/// This field was identified as the length field of some list and thus elided from the API. This function
/// computes the field's value again.
pub fn keycodes_per_modifier(&self) -> u8 {
    self.keycodes.len() / 8 as _
}
```
(Dunno if the actual implementation should panic on incorrect values instead of silently doing the wrong thing...)
(Also: Hints for good wording of the doc comment welcome)
