### ISSUE TITLE
Enums may have values that are not specified in the definitions

### ISSUE THREAD

**Issue by eduardosm** [psychon/x11rb#458]
The `xinput` command line tool can be used to print XInput 2 events (`xinput test-xi2`). Using the same tool to remove a master device (`xinput remove-master`) will produce the following event:
```
EVENT type 11 (HierarchyChanged)
    Changes happened:  [master removed]  [slave removed]  [slave detached]  [device disabled]
    device 2 [master pointer (3)] is enabled
    device 3 [master keyboard (2)] is enabled
    device 4 [slave pointer (2)] is enabled
    device 5 [slave keyboard (3)] is enabled
    device 6 [slave keyboard (3)] is enabled
    device 7 [slave keyboard (3)] is enabled
    device 8 [slave keyboard (3)] is enabled
    device 9 [slave keyboard (3)] is enabled
    device 10 [slave keyboard (3)] is enabled
    device 11 [slave keyboard (3)] is enabled
    device 12 [slave keyboard (3)] is enabled
    device 13 [slave pointer (2)] is enabled
    device 14 [<undefined> (0)] is disabled
    changes:  [master removed]      [device disabled]
    device 15 [<undefined> (0)] is disabled
    changes:  [master removed]      [device disabled]
    device 16 [<undefined> (0)] is disabled
    changes:    [slave removed]  [slave detached]  [device disabled]
    device 17 [<undefined> (0)] is disabled
    changes:    [slave removed]  [slave detached]  [device disabled]
```

What is shown as `[master pointer (3)]`, `[slave pointer (2)]`... is the `type` field from the `HierarchyInfo` structure:
https://github.com/psychon/x11rb/blob/3d8221da86b87e8c6651cc7437adba60b86c94c1/xcb-proto-1.14-1-g2b3559c/src/xinput.xml#L2379-L2386

The `DeviceType` is defined as:
https://github.com/psychon/x11rb/blob/3d8221da86b87e8c6651cc7437adba60b86c94c1/xcb-proto-1.14-1-g2b3559c/src/xinput.xml#L1606-L1612

The XML defines 1 to 5 as valid values, so the generated code will expect those values. However, in the event shown before, there value 0 can also appear, which causes a `ParseError` in x11rb.

**Comment by psychon** [comment]
The definition of `xXIHierarchyInfo` in `/usr/include/X11/extensions/XI2proto.h` calls the `type` field of what is `HierarchyInfo` in `xinput.xml` `use`. When sending an event, the function `GetDeviceUse` is used to compute this field: https://gitlab.freedesktop.org/xorg/xserver/-/blob/b5b529799a20f8a262066daeb726307c0631f208/Xi/xichangehierarchy.c#L87
This function can only return the five valid protocol values:
https://gitlab.freedesktop.org/xorg/xserver/-/blob/b5b529799a20f8a262066daeb726307c0631f208/Xi/xiquerydevice.c#L468-486
Uhm... since these zero fields occur at the end, could it be that the length field is somehow wrong? Could this simply be uninitialised memory containing only zero bytes?

**Comment by psychon** [comment]
Oh, I'm blind. It's right there in the code. The server always sends `MAXDEVICES` many devices in the event. The disabled ones get `0` as their use:
https://gitlab.freedesktop.org/xorg/xserver/-/blob/b5b529799a20f8a262066daeb726307c0631f208/Xi/xichangehierarchy.c#L106
I guess it's time for a bug report, but I am not sure where. The xcb-proto XML needs to be fixed (how? switch to `altenum`? Have a special enum with the "extra zeros"?)
The protocol specification also needs to be fixed since it does not allow what the server is sending. https://www.x.org/releases/X11R7.7/doc/inputproto/XI2proto.txt basically describes what the XML also describes.

Perhaps the best course of actions is to open a bug report at https://gitlab.freedesktop.org/xorg/xserver/-/issues and ask for guidance?

**Comment by eduardosm** [comment]
It seems that it does not really send `MAXDEVICES`, it just loops over all the possible IDs and includes the removed ones with `use = 0`.

**Comment by psychon** [comment]
https://gitlab.freedesktop.org/xorg/xserver/-/issues/1036

**Comment by eduardosm** [comment]
Fixing the server does not really fix the issue for us, because we cannot expect that everyone receives that fix (at least not soon).

Considering that we don't know where else there can be bugs (this is x11, there are more bugs for sure), maybe we should think a way of making x11rb less strict with enums.

**Comment by psychon** [comment]
Submitted https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/merge_requests/13 to xcb-proto to get the `0` to be allowed.

**Comment by eduardosm** [comment]
Fixed in https://github.com/psychon/x11rb/pull/545.
