### ISSUE TITLE
Semi-transparent windows

### ISSUE THREAD

**Issue by sandmor** [psychon/x11rb#531]
Is there a manner of do the alpha channel work?, I don't want only a solid background with alpha but the ability to setting the alpha value of each individual pixel and then they blend with the background.
EDIT: I want to draw an image and do its alpha pixels count
EDIT 2: Maybe this [works](https://magcius.github.io/xplain/article/composite.html) until I understand in this article the window buffer is move to a buffer in memory and then the xrender extension is used to draw it with alpha, that will achieve that I want to?

**Comment by psychon** [comment]
I think the [cairo-example](https://github.com/psychon/x11rb/blob/master/cairo-example/src/main.rs) shows how to create a window with an alpha channel. It certainly has the code to do so, but I do not have a composite manager currently, so I cannot test it.

So, first: X11 is older than transparency. ;-)
Due to this, it is kind of possible to get transparency, but not nicely. There needs to be a composite manager running. You can check if one is running by checking if the `_NET_WM_S0` selection is owned (see `composite_manager_running` in the cairo example).

Then, you need to create your window with the right visual (see `choose_visual` in the example) and color depth (32). There is a special standard PictFormat that needs to be supported. The code looks for that one.

Now that you have your window, you can draw to it. The render extension supports correct alpha blending and "fancy drawing". If you want to draw with core X11, you can specify colors in the form `0xAARRGGBB`. For example, `0x80008000` should be 50% transparent green. IIRC This uses pre-multiplied alpha, so the color channel should contain the color multiplied with the alpha value, as in this example.

> EDIT 2: Maybe this works

Well... yes and no. Using the composite extension is the composite manager's job. You can use that extension yourself, but then you are either implementing a composite manager or can only apply it to your own drawing (but then you already know the background and can just apply the alpha directly yourself).

**Comment by sandmor** [comment]
thank you, although looks like check if there is a composite manager, is not necessary currently, if there is not, simply the alpha will not work, right?

**Comment by psychon** [comment]
IIRC, in that case, the visual result will be as if there was a black background behind your window. This means that the window contents will be rather dark. But yes, the transparency will simply not work and everything should still work fine.

**Comment by eduardosm** [comment]
> I think the [cairo-example](https://github.com/psychon/x11rb/blob/master/cairo-example/src/main.rs) shows how to create a window with an alpha channel. It certainly has the code to do so, but I do not have a composite manager currently, so I cannot test it.

I confirm that it works correctly.
