### ISSUE TITLE
Registering ButtonPress and ButtonRelease to a window causes Access error

### ISSUE THREAD

**Issue by SpyrosRoum** [psychon/x11rb#542]
Hello, I am making a non re-parenting wm and I am trying to emulate the behavior of dwm so I can hold down the mod key + click and drag to move the window around.
The issue is that in my manage_window method when I try to change the attributes of a window so I receive ButtonPress and ButtonRelease I get an access error. Any idea why this might happen?

```rust
// This causes an error:
let events = ChangeWindowAttributesAux::default().event_mask(
            EventMask::ButtonPress
            | EventMask::ButtonRelease
            | EventMask::KeyPress
            | EventMask::KeyRelease
            | EventMask::PointerMotion
            | EventMask::EnterWindow
);
self.conn
    .change_window_attributes(window, &events)?
    .check()?;
```

```rust
// This does not:
let events = ChangeWindowAttributesAux::default().event_mask(
            EventMask::KeyPress
            | EventMask::KeyRelease
            | EventMask::PointerMotion
            | EventMask::EnterWindow
);
self.conn
    .change_window_attributes(window, &events)?
    .check()?;
```

Update: The issue seems to be with ButtonPress only
Edit: I see on the docs of X11 that only one client at a time can select for ButtonPress but I guess I am a little confused. 
I am sure I don't select it anywhere else, and in your basic wm example you select it for the frame of every created window?
Please help me understand what I am confusing here, and if you need more code let me know!

**Comment by psychon** [comment]
As you already noticed yourself (from https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#requests:ChangeWindowAttributes):

> only one client at a time can select for ButtonPress. An attempt to violate these restrictions results in an Access error

> I am sure I don't select it anywhere else,

A client is any connection to the X11 server. So, since you are writing a WM, I guess that whatever client created that window already asked for button press events.

Since you mention dwm:

dwm seems to set this event mask (https://git.suckless.org/dwm/file/dwm.c.html#l1060):
```c
XSelectInput(dpy, w, EnterWindowMask|FocusChangeMask|PropertyChangeMask|StructureNotifyMask);
```
The very next line calls [`grabbuttons`](https://git.suckless.org/dwm/file/dwm.c.html#l937). This function sends `GrabButton` events to register passive grabs for the buttons that it wants to know about.

For more information about `GrabButton`, see https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#requests:GrabButton
There is also a bit of docs for this request in the XML in xcb-proto. Perhaps this helps, but the docs containing the word "TODO" seems worrysome: https://docs.rs/x11rb/0.7.0/x11rb/protocol/xproto/fn.grab_button.html

I'll close since under the assumption that your question is answered, but feel free to disagree and reopen. We can also discuss things on a closed issue.

**Comment by SpyrosRoum** [comment]
Hey, thanks for the reply!
I've actually been trying to understand how grab_button works but I have a question, I am not sure what the event_mask argument should be.
It's *something* that implements Into<u16> but that doesn't help much at all. I tried to pass EventMask::ButtonPress but that doesn't implement Into<u16>, and I also tried to look for some sort of `SETofPOINTEREVENT` like it's in the original documentation but I couldn't find much. 
Any idea on that?

**Comment by psychon** [comment]
I just love the docs so much, I have to quote their reply to this question:

> event_mask - Specifies which pointer events are reported to the client.
> TODO: which values?

That's just great.... :-)

The XML is slightly better:
https://github.com/psychon/x11rb/blob/a29b84d5c9d4db5dd1a08a7343764f6dc3b2c9c9/xcb-proto-1.14-1-g2b3559c/src/xproto.xml#L2743
Okay, so it is a combination of `EventMask` values. That is the enum `x11rb::protocol::xproto::EventMask`. As you noticed, this enum does not implement `Into<u16>`, because it has values as large as `1 << 24`, which does not fit into 16 bits. Sigh.

Since you already found `SETofPOINTEREVENT`, the reference manual defines it as:

> POINTEREVENT | { ButtonPress, ButtonRelease, EnterWindow, LeaveWindow, PointerMotion, PointerMotionHint, Button1Motion, Button2Motion, Button3Motion, Button4Motion, Button5Motion, ButtonMotion, KeymapState }
-- | --

xcb-proto does not have a dedicated define for this, but it seems to be quite clearly the first few entries of the `EventMask` enum (up to `1 << 14`, so I guess it should really be `i16` and not `u16`? But that sign bit has no meaning...).

I guess this means that to produce the right value, you'll have to do something as ugly as `u32::from(EventMask::ButtonPress) as u16` or `u16::try_from(u32::from(EventMask::ButtonPress)).unwrap()` (with the `TryFrom` trait in scope).

@eduardosm Do you think we should open a dedicated issue about this? I have no idea what could be done about it.

**Comment by SpyrosRoum** [comment]
Ayy thank you, this makes sense, I thought it might be something like this at the end but I wasn't sure because of the uglyness haha

**Comment by eduardosm** [comment]
> xcb-proto does not have a dedicated define for this, but it seems to be quite clearly the first few entries of the `EventMask` enum (up to `1 << 14`, so I guess it should really be `i16` and not `u16`? But that sign bit has no meaning...).

I don't agree, I think we should stick to unsigned integers for bitmasks, because there isn't `From<i16> for u32` (and sign-extending right shifts do no make much sense there).

> Do you think we should open a dedicated issue about this? I have no idea what could be done about it.

I believe that it is the best we could do now, I'm not sure how to fix this either.
