### ISSUE TITLE
DPI awareness

### ISSUE THREAD

**Issue by sandmor** [psychon/x11rb#550]
How can I know the DPI of the screen used by my window? Also, how can I know when this change and get the new value?

**Comment by psychon** [comment]
Well... I'm not quite sure. What is "the" DPI?

There is the RandR extension: https://gitlab.freedesktop.org/xorg/proto/randrproto/-/blob/master/randrproto.txt
Via this extension, you can query the outputs that are present, their size in pixels and their size in mm. You can also ask for events when the outputs change.

Of course, your window can be visible on multiple outputs at once. No idea how one can handle that situation.

There is also stuff like `Xft.dpi`. This is specified via Xresources, see e.g. https://wiki.archlinux.org/index.php/X_resources. I also do not fully know they work. I think the `RESOURCE_MANAGER` property on the root window is involved. And perhaps `~/.Xdefaults`. I do not fully know.

**Comment by sandmor** [comment]
Thank you for the quick response, sorry if "the DPI" sounds weird, English is not my native language.
But, this is only half-response, I can use RandR to know the DPI at the window creation, but how I know if the DPI change? Is there an event for that?
And about the existence of the same window in multiple outputs... I will do something, do you know how I could know in which outputs it is in order to know its DPI?

**Comment by psychon** [comment]
> Thank you for the quick response, sorry if "the DPI" sounds weird, English is not my native language.

Sorry for my short answer. That's not what I meant, but I really did not explain what I mean.

"dots per inch" is a physical property of a monitor. This is unrelated to how large e.g. a button is on screen. With DPI awareness, you can ensure that something that should be 1 cm large really is 1 cm on screen. That's a bit unrelated to "I want all stuff on screen to be larger", but of course this problem comes up more often with HighDPI stuff.
Anyway, my impression is that there are programs out there that make a difference between "DPI used for fonts" and "scaling used for all other UI elements".

So, basically, I do not really know what I am talking about, but there is more than "one DPI", so it is not "the (one) DPI" but more like "various DPIs". That's what I was trying to hint to, but definitely did not say. Sorry.

> I can use RandR to know the DPI at the window creation, but how I get notified if the DPI change? Is there an event for that?

You can know the position of your window on screen with core X11 by asking for ConfigureNotify events. These inform you when the window moves, e.g. to another screen.
Via RandR, you can ask for events when the screen configuration changes (e.g. a new monitor is connected and turned on, or an existing monitor is switched to a different resolution). The way to do this seems to be `RRSelectInput` (that's the name from randrporo; xcb-proto seems to call this `SelectInput` and thus x11rb calls this `select_input` in `x11rb::protocol::randr`).

> And about the existence of the same window in multiple outputs... I will do something, do you know how I could know in which outputs it is in order to know its DPI?

Quick tour of RandR:
- You have multiple CRTCs. Each CRTC displays a portion of the root window. For example, some CRTC can display the rectangle with top left corner (0, 0) and size (1920, 1080). I think that `/usr/bin/xrandr` does not actually show CRTCs (unless you use `--verbose`, but that output looks unreadable).
- A CRTC can have multiple outputs. This is supposed to correspond to a physical monitor that can display stuff. An output has a size in mm.

Thus, the same CRTC can be shown on multiple outputs (think: "clone mode").

However, you can also have the same rectangle on the root window to be visible on multiple CRTCs. As an imagine, imagine a CRTC that shows (0, 0) to (800, 600) and another one that shows (400, 300) and also has size (800, 600). These two CRTCs would overlap in the middle. And each CRTC could drive more than one output. It's complicated...

RandR 1.5 then added the new concept of monitors. There are screens out there that have a higher resolution than what HDMI support. Thus, these consist of two separate... well... monitors? that can be driven via two cables and look to the computer as if they were two completely separate "things". You have to configure them to be side-by-side to get correct results.
All of this complexity is visible in RandR. You see two CRTCs and two outputs.
To hide this, RandR 1.5 added monitors. A monitor has a name, a position on the root window in pixels and a size in millimeters. The two outputs in the example above should be represented by a single monitor.

If you want to support X11 servers that do not support RandR 1.5 is your call. I do not know how common it is. I would guess that the nvidia binary blob had (has?) problems with it.

Now we are already at three different cases and lots of complications (there is not one single screen):
- no RandR supported by the X11 server
- only RandR older than 1.5 supported by the X11 server
- RandR 1.5 or newer supported by the X11 server

If you want, I can cook up a quick example on all of this (next weekend).

However, all of the above ignores `Xft.dpi`. See https://wiki.archlinux.org/index.php/HiDPI#X_Resources (although that does not really help). https://github.com/linebender/druid/pull/1389 also seems to be loosely related.

Also, in case it is not entirely clear: I also do not know what "the right way" is. I have a basic understanding of RandR and I know a bit about how X resources work and that `Xft.dpi` is a think (that is only supposed to affect font rendering).

**Comment by sandmor** [comment]
Thank you, the example would be useful but I can wait don't worry, about the kind of DPI that I am pointing to achieve, I only want to:
> ensure that something that should be 1 cm large really is 1 cm on screen

**Comment by psychon** [comment]
Urgh. I forgot how much fun RandR is.

Anyway, the following draws a 2 cm line and I measured it to really be 2 cm on both of my screens (which have different DPIs). I did not test any of the dynamic code that re-queries the screen information when e.g. a new screen is connected, but I see no reason why it would not work. I am sending the correct `randr_select_input` request, so it must work!
```rs
use std::convert::TryFrom;
use std::convert::TryInto;

use x11rb::connection::Connection;
use x11rb::errors::{ReplyError, ReplyOrIdError};
use x11rb::protocol::xproto::{CreateWindowAux, CreateGCAux, CoordMode, EventMask, Screen, Point, Window, WindowClass, ConnectionExt as _};
use x11rb::protocol::randr::{self, ConnectionExt as _};
use x11rb::protocol::Event;

fn calc_dots_per_centimeter(pixel: (u16, u16), millimeters: (u32, u32)) -> u16 {
    fn helper(pixel: u16, millimeters: u32) -> u16 {
        let pixel = u32::from(pixel);
        let value = pixel * 10 / millimeters;
        u16::try_from(value).unwrap_or(u16::MAX)
    }
    helper(pixel.0, millimeters.0).max(helper(pixel.1, millimeters.1))
}

#[derive(Debug, Copy, Clone, Eq, PartialEq)]
enum ServerRandRSupport {
    None,
    RandRScreenResources,
    RandRScreenResourcesCurrent,
    RandRMonitors
}

impl ServerRandRSupport {
    fn new(conn: &impl Connection, screen: &Screen) -> Result<Self, ReplyError> {
        if conn.extension_information(randr::X11_EXTENSION_NAME)?.is_none() {
            Ok(ServerRandRSupport::None)
        } else {
            use randr::NotifyMask::*;

            // Monitor support was added in RandR 1.5
            let version = conn.randr_query_version(1, 5)?;
            conn.randr_select_input(screen.root, ScreenChange | CrtcChange | OutputChange)?;
            let version = version.reply()?;
            match (version.major_version, version.minor_version) {
                (major, _) if major >= 2 => Ok(ServerRandRSupport::RandRMonitors),
                (1, minor) if minor >= 5 => Ok(ServerRandRSupport::RandRMonitors),
                (1, minor) if minor >= 3 => Ok(ServerRandRSupport::RandRScreenResourcesCurrent),
                (1, minor) if minor >= 2 => Ok(ServerRandRSupport::RandRScreenResources),
                // Dunno what to do with this ancient RandR version
                _ => Ok(ServerRandRSupport::None),
            }
        }
    }

    fn query(self, conn: &impl Connection, screen: &Screen) -> Result<Vec<OutputInfo>, ReplyError> {
        match self {
            Self::None => Ok(vec![OutputInfo::from_screen(screen)]),
            Self::RandRScreenResources | Self::RandRScreenResourcesCurrent => {
                let (crtcs, timestamp) = if self == Self::RandRScreenResourcesCurrent {
                    let reply = conn.randr_get_screen_resources_current(screen.root)?.reply()?;
                    (reply.crtcs, reply.config_timestamp)
                } else {
                    let reply = conn.randr_get_screen_resources(screen.root)?.reply()?;
                    (reply.crtcs, reply.config_timestamp)
                };
                // Collect the information about all CRTCs
                let mut result = Vec::new();
                for &crtc in &crtcs {
                    let crtc_info = conn.randr_get_crtc_info(crtc, timestamp)?.reply()?;
                    let position = (crtc_info.x, crtc_info.y);
                    let size_px = (crtc_info.width, crtc_info.height);
                    for &output in &crtc_info.outputs {
                        let output_info = conn.randr_get_output_info(output, timestamp)?.reply()?;
                        let size_mm = (output_info.mm_width, output_info.mm_height);
                        result.push(OutputInfo::from_rectangle(position, size_px, size_mm));
                    }
                }
                Ok(result)
            },
            Self::RandRMonitors => {
                let monitors = conn.randr_get_monitors(screen.root, true)?.reply()?;
                let result = monitors.monitors.iter()
                    .map(|info| OutputInfo::from_rectangle((info.x, info.y), (info.width, info.height), (info.width_in_millimeters, info.height_in_millimeters)))
                    .collect();
                Ok(result)
            },
        }
    }
}

#[derive(Debug)]
struct OutputInfo {
    dots_per_centimeter: u16,
    // Pixel coordinates of the are that is covered
    x: i16,
    y: i16,
    width: u16,
    height: u16,
}

impl OutputInfo {
    fn contains(&self, position: (i16, i16), size: (u16, u16)) -> bool {
        fn helper((output_pos, output_size): (i16, u16), (win_pos, win_size): (i16, u16)) -> bool {
            i64::from(output_pos) < i64::from(win_pos) + i64::from(win_size) && i64::from(output_pos) + i64::from(output_size) >= i64::from(win_pos)
        }
        helper((self.x, self.width), (position.0, size.0)) && helper((self.y, self.height), (position.1, size.1))
    }

    fn from_screen(screen: &Screen) -> Self {
        let pos = (0, 0);
        let size_px = (screen.width_in_pixels, screen.height_in_pixels);
        let size_mm = (screen.width_in_millimeters.into(), screen.height_in_millimeters.into());
        Self::from_rectangle(pos, size_px, size_mm)
    }

    fn from_rectangle((x, y): (i16, i16), (width, height): (u16, u16), (width_in_mm, height_in_mm): (u32, u32)) -> Self {
        let dots_per_centimeter = calc_dots_per_centimeter((width, height), (width_in_mm, height_in_mm));
        Self {
            dots_per_centimeter,
            x,
            y,
            width,
            height,
        }
    }
}

fn create_window(conn: &impl Connection, screen: &Screen, (x, y): (i16, i16), (width, height): (u16, u16)) -> Result<Window, ReplyOrIdError> {
    let window = conn.generate_id()?;
    let win_aux = CreateWindowAux::new()
        .event_mask(EventMask::Exposure | EventMask::StructureNotify)
        .background_pixel(screen.white_pixel);
    conn.create_window(
        screen.root_depth,
        window,
        screen.root,
        x,
        y,
        width,
        height,
        0,
        WindowClass::InputOutput,
        0,
        &win_aux
    )?;
    Ok(window)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (conn, screen_num) = x11rb::connect(None)?;
    let screen = &conn.setup().roots[screen_num];

    let mut position = (0, 0);
    let mut size = (200, 200);

    let win_id = create_window(&conn, screen, position, size)?;
    conn.map_window(win_id)?;

    let font_id = conn.generate_id()?;
    let gc_id = conn.generate_id()?;
    conn.open_font(font_id, "7x13".as_bytes())?;
    conn.create_gc(gc_id, win_id, &CreateGCAux::new()
                   .foreground(screen.black_pixel)
                   .background(screen.white_pixel)
                   .font(font_id))?;
    conn.close_font(font_id)?;

    let randr_support = ServerRandRSupport::new(&conn, screen)?;
    let mut output_infos = randr_support.query(&conn, screen)?;

    loop {
        conn.flush()?;
        let event = conn.wait_for_event()?;
        //println!("{:?}", event);
        match event {
            Event::Expose(event) => {
                if event.count == 0 {
                    let mut offset = 0;
                    for info in &output_infos {
                        if !info.contains(position, size) {
                            continue;
                        }

                        let length_in_cm = 2;
                        let length = length_in_cm * u32::from(info.dots_per_centimeter);
                        offset += 20;
                        let points = [
                            Point { x: 120, y: offset },
                            Point { x: length.try_into().unwrap_or(i16::MAX), y: 0 },
                        ];
                        let text = format!("{} dots per cm", info.dots_per_centimeter);
                        conn.image_text8(win_id, gc_id, 10, offset + 5, text.as_bytes())?;
                        conn.poly_line(CoordMode::Previous, win_id, gc_id, &points)?;
                    }
                }
            }
            Event::ConfigureNotify(event) => {
                let translation = conn.translate_coordinates(win_id, screen.root, 0, 0)?.reply()?;
                size = (event.width, event.height);
                position = (translation.dst_x, translation.dst_y);

                // I'm too lazy to check if something changed, so just force a repaint
                conn.clear_area(true, win_id, 0, 0, 0, 0)?;
            }
            Event::RandrNotify(_) | Event::RandrScreenChangeNotify(_) => {
                output_infos = randr_support.query(&conn, screen)?;

                // Force a repaint
                conn.clear_area(true, win_id, 0, 0, 0, 0)?;
            }
            _ => {}
        }
    }
}
```

**Comment by sandmor** [comment]
Thank you so much, although I have not tried the example yet

**Comment by psychon** [comment]
@sandmor What's the state of this issue? What is needed before it can be closed?

(For future readers: The above was written for / tested with x11rb 0.7)

**Comment by sandmor** [comment]
Thank you, the code works, I will figure out myself if I have following issues

**Comment by sandmor** [comment]
Sorry for the delay
