### ISSUE TITLE
How can I support icccm/ewmh using x11rb

### ISSUE THREAD

**Issue by SpyrosRoum** [psychon/x11rb#573]
Hello, I am wondering if it's possible to cover icccm and ewmh in my window manager using x1rb.
I know in C xcb-icccm exists but I haven't been able to find something similar for Rust.
[xcb-util](https://crates.io/crates/xcb-util) is a thing but it uses [xcb](https://crates.io/crates/xcb) for the backend so it's not really compatible with x11rb.

For a more concrete example, I was trying to get transient info for windows but I was unable to find any way to do this

**Comment by psychon** [comment]
Most of EWMH just specifies window properties, so you just have to query the right window property.

> For a more concrete example, I was trying to get transient info for windows but I was unable to find any way to do this

This comes from ICCCM § 4.1.2.6:

> The WM_TRANSIENT_FOR property (of type WINDOW) contains the ID of another top-level window.  [...]

So, you query a window's `WM_TRANSIENT_FOR` property of type `WINDOW` and get a window ID. Something like `conn.get_property(false, window_id, AtomEnum::WM_TRANSIENT_FOR, AtomEnom::WINDOW, 0, 1).unwrap().reply().value32().next().unwrap()`. (Of course, you should avoid `unwrap`s in your actual code.)

Since this is just a one-liner, this library does not contain an extra wrapper function for this.

The code in `libxcb-icccm` does basically the same. Here is a random GitHub repo that Google found:

https://github.com/iplinux/xcb-util/blob/e3d56200f322c6e25a80381d27fe37205826a4c1/icccm/icccm.c#L278-L312

**Comment by SpyrosRoum** [comment]
Thank you this helps a lot since I'm still trying to wrap my head around how icccm and ewmh works with properties and such :sweat_smile:

**Comment by psychon** [comment]
Two more data points:
- I searched ICCCM for "transient" to find ICCCM § 4.1.2.6 in the example above. I do not know this stuff by heart. :-)
- You should the program `/usr/bin/xprop` on your system. When you run it, you can click on a window and then are shown all of its window properties. Random example from its output: `_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 21, 1`. This is the property `_NET_FRAME_EXTENTS` of type `CARDINAL` and it contains four numbers. Since its name starts with `_NET`, it should be documented in EWMH. ICCCM properties start with `WM_`.
