### ISSUE TITLE
Bug that could prevent certain requests from being read properly

### ISSUE THREAD

**Issue by not-a-seagull** [psychon/x11rb#576]
I recently encountered this bug while developing breadx, and I'm about 99% sure this issue affects this crate as well.

Consider [this segment of code here](https://github.com/psychon/x11rb/blob/master/src/rust_connection/stream.rs#L444).

```
let msg = loop {
  match recvmsg(fd, &iov[..], Some(&mut cmsg), MsgFlags::empty()) {
      Ok(msg) => break msg,
      // try again
      Err(nix::Error::Sys(nix::errno::Errno::EINTR)) => {}
      Err(e) => return Err(nix_error_to_io(e)),
    }
 };
```

Specifically, consider the `Ok(msg) => break msg` line. Let's say `recvmsg` doesn't read all of the bytes of the request, which is a conceivable case with very large replies and events (e.x. GLX's `GetVisualConfig`). In this case, `recvmsg` will return a message with `bytes` field not equal to the length of the IO vector, and you would need to call `recvmsg` again

**Comment by psychon** [comment]
Heh. Thanks for the hint. I was just reading your PR on breadX to figure out what the problem was. :-)

However, we are already handling partial reads. I can't point to a specific line of code, but this whole file has basically this purpose: https://github.com/psychon/x11rb/blob/master/src/rust_connection/packet_reader.rs

The `PacketReader` contains a read buffer. This is the buffer that we `recvmsg()` into. This is done by the `read` calls in `try_read_packets()`. After we read something "from the wire", we try to take X11 packets out of this buffer. Each X11 packet has at least length 32, so there is a `vec![0; 32]` in `self.pending_packet`. We try to copy data into this (and keep track with `already_read` how much we already read in previous calls). When we got 32 bytes of data, we can be sure to also have the length field, so `extra_length()` is used to read the length field from the packet. Then, the `Vec` is resized accordingly and we continue "moving bytes around". When we now read the whole X11 packet, it is pushed into a `Vec` of received packets and given of to the caller.

I thought I had just found a bug in this code, but no, that's not the case.... Thanks for making me double-check.

Why we do this separately: `RustConnection` allows swapping the `DefaultStream` that is used for reading and writing with an implementation of your choice (via the `Stream` trait), so a "layer above that" has to handle partial reads. This is the `PacketReader`.
(`Stream` is basically a combination of `Read` and `Write`, but extended with FD passing, and also a `poll()` method that allows waiting until the stream is readable or writable, whatever happens first.)
