### ISSUE TITLE
Help with `xkb_set_controls`

### ISSUE THREAD

**Issue by lmburns** [psychon/x11rb#648]
I have tried to find an example of someone using this command on Github, but was unable to find an one, and I have browsed over this crate's source code and the [`C` source code of `libx11`](https://github.com/freedesktop/xorg-libX11/blob/master/src/xkb/XKBCtrls.c) to try and see if I am doing something wrong. I have been unable to find anything that can help me, so I am creating an issue to ask here.

I am trying to allow the user to **set the key repeat-delay and the key repeat-interval** in the program that I am writing. So, I have browsed over the `xset` source code and the `kbdrate` source code as well, to try and see if I can figure out anything. Another idea I had was to switch my connection from an explicit `RustConnection` to the trait `Connection`, which did nothing.

This is the code that I have written to try and set the values.

```rust
// Note that `conn` here refers to a `RustConnection`
// If this reply is printed, `repeat_delay` and `repeat_interval` are shown
let reply = self.conn
    .xkb_get_controls(ID::USE_CORE_KBD.into())
    .context("failed to get XKB `GetControlsReply`")?
    .reply()
    .context("failed to get XKB `GetControlsReply` reply")?;

self.conn
    .xkb_set_controls(
        ID::USE_CORE_KBD.into(),
        0_u8,                                    // affect_internal_real_mods
        reply.internal_mods_real_mods,           // internal_real_mods
        0_u8,                                    // affect_ignore_lock_real_mods
        reply.ignore_lock_mods_real_mods,        // ignore_lock_real_mods
        0_u8,                                    // affect_internal_virtual_mods
        reply.internal_mods_vmods,               // internal_virtual_mods
        0_u8,                                    // affect_ignore_lock_virtual_mods
        reply.ignore_lock_mods_vmods,            // ignore_lock_virtual_mods
        reply.mouse_keys_dflt_btn,               // mouse_keys_dflt_btn
        reply.groups_wrap,                       // groups_wrap
        reply.access_x_option,                   // access_x_options
        0_u16,                                   // affect_enabled_controls
        reply.enabled_controls,                  // enabled_controls
        0_u32,                                   // change_controls
        u16::from(500 | BoolCtrl::REPEAT_KEYS),  // repeat_delay
        u16::from((1000 / 50) | BoolCtrl::REPEAT_KEYS), // repeat_interval
        reply.slow_keys_delay,                   // slow_keys_delay
        reply.debounce_delay,                    // debounce_delay
        reply.mouse_keys_delay,                  // mouse_keys_delay
        reply.mouse_keys_interval,               // mouse_keys_interval
        reply.mouse_keys_time_to_max,            // mouse_keys_time_to_max
        reply.mouse_keys_max_speed,              // mouse_keys_max_speed
        reply.mouse_keys_curve,                  // mouse_keys_curve
        reply.access_x_timeout,                  // access_x_timeout
        reply.access_x_timeout_mask,             // access_x_timeout_mask
        reply.access_x_timeout_values,           // access_x_timeout_values
        reply.access_x_timeout_options_mask,     // access_x_timeout_options_mask
        reply.access_x_timeout_options_values,   // access_x_timeout_options_values
        &reply.per_key_repeat,                   // per_key_repeat
    )
    .context("failed to set XKB controls")?;
```

I added the `BoolCtrl::REPEAT_KEYS` to see if it was looking for a specific mask, because in the `C` source code it checks for `XkbRepeatKeysMask`. When following that variable to `XKB.h`, it is define as
```
#define	XkbRepeatKeysMask	 (1L << 0)
```
and so is `BoolCtrl::REPEAT_KEYS`. I have also tried this when not using the `BoolCtrl`, and both haven't done anything. I am unsure if the `0_u8`s in the above example need to be specified as something other than what they are, or if I am missing something as simple as a `self.conn.sync()` or `self.conn.flush()` (which I've tried both and couldn't get to work).

**Comment by psychon** [comment]
I don't really have much knowledge about XKB, so I took a quick look at https://www.x.org/docs/XKB/XKBproto.pdf and.... now I still have no clue.

Okay, time for experiments!

The link above says about XkbSetControls:

> This request sets the keyboard controls indicated in changeControls for the keyboard
> specified by deviceSpec. Each bit that is set in changeControls indicates that one or
> more of the other request fields should be applied, as follows:

If I understand your code correctly, you are setting `change_controls` to `0`, which I guess means "do nothing". The following program seems to work for me:

```rs
use x11rb::protocol::xkb::{self, ConnectionExt};

fn print_info(conn: &impl ConnectionExt) -> Result<(), Box<dyn std::error::Error>> {
    let reply = conn
        .xkb_get_controls(xkb::ID::USE_CORE_KBD.into())?
        .reply()?;
    println!("reply: {:?}", reply);
    println!(
        "{:?} delay, {:?} interval, per key: {:?}",
        reply.repeat_delay, reply.repeat_interval, reply.per_key_repeat
    );
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (conn, _) = x11rb::connect(None)?;
    conn.xkb_use_extension(1, 0)?;

    print_info(&conn)?;

    conn.xkb_set_controls(
        xkb::ID::USE_CORE_KBD.into(),
        0,
        0u8,
        0u8,
        0u8,
        0u8,
        0u8,
        0u8,
        0u8,
        0u8,
        0u8,
        0u8,
        0u8,
        0u8,
        xkb::BoolCtrl::REPEAT_KEYS,
        1234u16,
        5678u16,
        0u16,
        0u16,
        0u16,
        0u16,
        0u16,
        0u16,
        0i16,
        0u16,
        0u8,
        0u8,
        0u8,
        0u8,
        &[0; 32],
    )?
    .check()?;

    print_info(&conn)?;

    Ok(())
}
```
I use `check()?` on the request since at some point this request caused an error and since this example doesn't have any main loop, that error was silently ignored.

Anyway, I put the two outputs of `print_info` into two separate files and used `git diff --word-diff` to compare them. `git` says that the two replies are the same, except for:

- Different `sequence` number. This is expected and has no significance outside of x11rb's reply handling code.
- Different `repeat_delay` value.
- Different `repeat_interval` value.

I did not actually test whether key repeat now behaves differently, but I would expect so.

I hope this is enough of a reply that I can close this issue. Feel free to disagree and tell me to reopen.

**Comment by lmburns** [comment]
Thank you very much for this! I guess I wasn't aware of what `check` did, but this did fix my issue and `xset` also recognized the changes when comparing outputs before and after. I also wasn't aware that fields that didn't need to be changed could be left untouched.

I will also use that `pdf` you have attached from now on, really helpful documentation. I had been reading over their documentation on the website.

**Comment by psychon** [comment]
> I guess I wasn't aware of what check did, 

Just to make this clearer: It checks whether the request generated an X11 error response and returns this error, if any.

Implementation detail: It does a `GetInputFocus` request and waits for the reply. Since the X11 server handles requests in-order, by the time the reply to `GetInputFocus` arrives, any X11 errors from earlier requests must already be received, too. That way it can check if there is a matching error (via the sequence number contained in the error).
