### ISSUE TITLE
Move away from Nix

### ISSUE THREAD

**Issue by notgull** [psychon/x11rb#770]
[`nix` is planning an MSRV bump to 1.63.0](https://github.com/nix-rust/nix/issues/1750). Given the relative recency of the 1.63 release, as well as `x11rb`'s relatively lax MSRV, I see two paths:

- Bump our MSRV to 1.63 as well.
- Port this code away from `nix`.

[`rustix`](https://crates.io/crates/rustix) may be a potential option to move to.

**Comment by SUPERCILEX** [comment]
Saw this issue referenced from nix and thought I'd throw in my opinion. I'm actually quite happy with rustix: they use a raw syscall backend by default on linux which means libc is no longer an optimization barrier. In practice, I've seen instruction count savings of multiple % for syscall heavy code. So as long as you're cool with not going through libc for syscalls on linux (which some people argue is wrong), then I'd say rustix is a good choice.

rustix also renames stuff to be clearer which I thought was weird at first, but I've come around to it because they have doc aliases for anything that's been renamed so you can still search for the definitions from the man page.

The one downside is that the lib is driven by the bytecodealliance, so you have to wonder where their interests are. That said, I see a long-term path to rustix becoming the de facto lib just because of the perf improvements and extra money/time they have to throw at the project.

**Comment by psychon** [comment]
We do not seem use much of nix:
```
$ git grep 'use nix::' | sort -u
x11rb/examples/xclock_utc.rs:    use nix::poll::{poll, PollFd, PollFlags};
x11rb/src/rust_connection/stream.rs:    use nix::fcntl::{fcntl, FcntlArg, FdFlag};
x11rb/src/rust_connection/stream.rs:    use nix::fcntl::{fcntl, FcntlArg, OFlag};
x11rb/src/rust_connection/stream.rs:            use nix::poll::{poll, PollFd, PollFlags};
x11rb/src/rust_connection/stream.rs:    use nix::sys::socket::{connect, socket, AddressFamily, SockFlag, SockType, UnixAddr};
x11rb/src/rust_connection/stream.rs:    use nix::sys::socket::MsgFlags;
x11rb/src/rust_connection/stream.rs:            use nix::sys::socket::{recvmsg, ControlMessageOwned};
x11rb/src/rust_connection/stream.rs:    use nix::sys::socket::{sendmsg, ControlMessage, MsgFlags, SockaddrLike};
```
Basically:
- `poll` (check if socket is readable/writable)
- abstract unix sockets
- FD passing (sendmsg, recvmsg)

So, yeah, rustix should be able to do that. Or perhaps something else can. The later two items AFAIR already have some work being done to add them to the standard library.

**Comment by psychon** [comment]
Actually, perhaps we can just stay at an old nix version? Their changes look semver-incompatible, so we could avoid them for a while. And nix feels to me to be more "well established", meaning that it is more likely that something will already depend on nix even without x11rb. That might make the "combined product" lighter than if we were to use rustix.

But... all of this is mostly guesswork. Dunno...
