### ISSUE TITLE
Maximum number of clients reached for connection in lazy_static and other singletons within a multi-threaded loop

### ISSUE THREAD

**Issue by donicrosby** [psychon/x11rb#794]
I'm currently working on a program using the game engine Bevy and require access to the X11 server on Linux to perform some action to respond when the user changes their focused window. I have attempted to put the RustConnection in all sorts of singletons or one-shot objects and after the program runs for a few minutes I receive a segfault from the max number of clients reached from the X11 server.

In order to stop this from happening how can I have the RustConnection be used by multiple threads but not spawn a new X11 server connection every time a new thread accesses the Connection? Is there a way to close the connection to the X11 Display other than dropping the connection? Or do I need to convert the connection to a Stream then use the Setup struct to connect the thread to the current connection without adding a new client?

**Comment by eduardosm** [comment]
If you are getting segfaults, your are probably having a memory exhaustion issue rather than reaching the maximum number of clients.

It looks like you are creating an unbounded number of `RustConnection`s which you never drop, causing a memory (and socket) leak. Closing the socket without dropping the `RustConnection` will not get rid of memory leaks.

`RustConnection` is `Send` and `Sync`, so you can share a single instance across threads by placing it inside an [`Arc`](https://doc.rust-lang.org/stable/std/sync/struct.Arc.html) that can be easily cloned and passed to different threads. When all the `Arc`s are dropped, the wrapped `RustConnection` will be dropped.

**Comment by psychon** [comment]
Uhm... do you have some code example that reproduces your problem? I feel like I am missing a lot about what is actually going on here.

I'll try to answer the actual questions, but I doubt it will be very useful.

> how can I have the RustConnection be used by multiple threads but not spawn a new X11 server connection every time a new thread accesses the Connection?

Assuming https://docs.rs/once_cell/latest/once_cell/ is available (code is untested, but should illustrate the idea):
```rust
use once_cell::sync::OnceCell;
use x11rb::rust_connection::RustConnection;
fn get_connection() -> &'static RustConnection {
  static CONNECTION: once_cell::sync::OnceCell<RustConnection> = OnceCell::new();
  CONNECTION.get_or_init(|| RustConnection::connect(None).unwrap())
}
```
Now every thread should be able to use `get_connection()` and use the resulting connection.

> Is there a way to close the connection to the X11 Display other than dropping the connection?

No. This is Rust and Rust uses RAII. Dropping things is the way that cleanup is done.

> Or do I need to convert the connection to a Stream then use the Setup struct to connect the thread to the current connection without adding a new client?

Uhm.... The best answer that I can give here is "no".

**Comment by donicrosby** [comment]
So it turns out that another library used did not manage it's own x11 connections properly causing the segfault.
