### ISSUE TITLE
Get name of window manager

### ISSUE THREAD

**Issue by andreykaere** [psychon/x11rb#798]
Hi! I am trying to write a function, that returns a name of window manager, this is my attempt:
```rust
pub fn get_current_wm() -> Result<String, Box<dyn Error>> {
    let (conn, screen_num) = x11rb::connect(None)?;
    let screen = &conn.setup().roots[screen_num];

    let net_supporting_wm_check = conn
        .intern_atom(false, b"_NET_SUPPORTING_WM_CHECK")?
        .reply()?
        .atom;

    let property = conn
        .get_property(
            false,
            screen.root,
            net_supporting_wm_check,
            AtomEnum::STRING,
            0,
            1024,
        )?
        .reply()?;

    let window_id = std::str::from_utf8(&property.value)?.parse()?;

    let net_wm_name = conn
        .intern_atom(false, b"_NET_WM_NAME(UTF8_STRING)")?
        .reply()?
        .atom;

    let property = conn
        .get_property(false, window_id, net_wm_name, AtomEnum::STRING, 0, 1024)?
        .reply()?;

    Ok(String::from_utf8(property.value)?)
}
```
However it panics, because output of "_NET_SUPPORTING_WM_CHECK" is empty. However testing it with `xprop`, it workes as expected (i.e. in that atom _NET_SUPPORTING_WM_CHECK root window contains id of some window, _NET_WM_NAME of which is desired name). Can you please help me to get it working?:) Thank you in advance!

**Comment by andreykaere** [comment]
I got solved it by this code, but I don't get it from where I should know that I should use `from_le_bytes` and not `from_ge_bytes`:
```rust
// https://stackoverflow.com/questions/758648/find-the-name-of-the-x-window-manager
pub fn get_current_wm() -> Result<String, Box<dyn Error>> {
    let (conn, screen_num) = x11rb::connect(None)?;
    let screen = &conn.setup().roots[screen_num];

    let atoms = AtomCollection::new(&conn)?;
    let atoms = atoms.reply()?;

    let property = conn
        .get_property(
            false,
            screen.root,
            atoms._NET_SUPPORTING_WM_CHECK,
            AtomEnum::WINDOW,
            0,
            1024,
        )?
        .reply()?;

    let wm_window_id =
        u32::from_le_bytes(property.value[..].try_into().unwrap());

    let property = conn
        .get_property(
            false,
            wm_window_id,
            atoms._NET_WM_NAME,
            atoms.UTF8_STRING,
            0,
            1024,
        )?
        .reply()?;

    let wm_name = String::from_utf8(property.value)?;

    Ok(wm_name)
}
```

**Comment by psychon** [comment]
Why don't you just query `_NET_WM_NAME` on the root window? That should be easier. But okay, via `_NET_SUPPORTING_WM_CHECK`....
```rust
use x11rb::atom_manager;
use x11rb::connection::Connection;
use x11rb::protocol::xproto::*;

atom_manager! {
    pub AtomCollection: AtomCollectionCookie {
        WM_PROTOCOLS,
        WM_DELETE_WINDOW,
        _NET_WM_NAME,
        UTF8_STRING,
        _NET_SUPPORTING_WM_CHECK,
    }
}

// https://stackoverflow.com/questions/758648/find-the-name-of-the-x-window-manager
pub fn get_current_wm() -> Result<String, Box<dyn std::error::Error>> {
    let (conn, screen_num) = x11rb::connect(None)?;
    let screen = &conn.setup().roots[screen_num];

    let atoms = AtomCollection::new(&conn)?.reply()?;

    let property = conn
        .get_property(
            false,
            screen.root,
            atoms._NET_SUPPORTING_WM_CHECK,
            AtomEnum::WINDOW,
            0,
            1024,
        )?
        .reply()?;

    // "Your" code used unwrap(), so I feel fine using unwrap() here, too.
    // Still, it would be better to invent some error here instead.
    let wm_window_id = property.value32().unwrap().next().unwrap();

    let property = conn
        .get_property(
            false,
            wm_window_id,
            atoms._NET_WM_NAME,
            atoms.UTF8_STRING,
            0,
            1024,
        )?
        .reply()?;

    let wm_name = String::from_utf8(property.value)?;

    Ok(wm_name)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("{:?}", get_current_wm()?);
    Ok(())
}
```

Specifically, I replaced 
```rust
    let wm_window_id =
        u32::from_le_bytes(property.value[..].try_into().unwrap());
```
with
```
    let wm_window_id = property.value32().unwrap().next().unwrap();
```
`value32()` returns `Option<impl Iterator<Item = u32>>`. This function actually checks that `property.format == 32`. If that is not the case, then `None` is returned (first `unwrap()`). The second `unwrap()` is then for the case where this property is empty.

> but I don't get it from where I should know that I should use from_le_bytes and not from_ge_bytes:

It's actually native endian (`from_ne_bytes` I guess) and you can let x11rb do this for you. There is a `TryParse` trait in x11rb that hides this. Instead of `from_le_bytes` you could use `u32::try_parse(&property.value)`. The above still hides that from the user some more.

**Comment by andreykaere** [comment]
Why do you prefer this
> `let wm_window_id = property.value32().unwrap().next().unwrap();`
over that
`u32::try_parse(&property.value)`
And what does it mean `property.format == 32`?

Regarding your question about checking _NET_WM_NAME on root window -- that doesn't work. At least in case bspwm. I don't know if that should work in general, but I think that the process, described in the link above, should work for almost all window managers ... And why do you think that atom _NET_WM_NAME should be set? Where is that specified?

**Comment by psychon** [comment]
> Why do you prefer this

Uhm... no good reason, I guess. I just followed the API that exists, but yeah, for this case using the `TryParse` trait directly might be beneficial.

> And what does it mean property.format == 32?

The X11 server does most of the byte swapping for the library users. A property can be in format 8, 16, or 32. When a client with a different endianness (big / little) than the X11 server interacts with a property, the server does the necessary endianness conversions.

Since these days everything is little endian, I guess it does not matter so much anywhere.

> Where is that specified?

To be honest, I am using i3 and simply checked which properties it sets. But you are right, EWMH does not actually require this. It only says: https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm45529331583248

>  The Window Manager MUST set this property on the root window to be the ID of a child window created by himself, to indicate that a compliant window manager is active. The child window MUST also have the _NET_SUPPORTING_WM_CHECK property set to the ID of the child window. The child window MUST also have the _NET_WM_NAME property set to the name of the Window Manager.
