### ISSUE TITLE
WM_NAME: STRING vs UTF8_STRING

### ISSUE THREAD

**Issue by andreykaere** [psychon/x11rb#809]
Hi! So, as the title says, sometimes WM_NAME is represented as STRING atom and sometimes as UTF8_STRING. And this is just half of the problem, because we can just try it one way and if it will give empty result, we will do it the other way. But my main question is: if it is STRING - which encoding is it? If I look at the `.format` field of the `GetPropertyReply`, it always says "8", however sometimes it is not UTF8, because some chars are broken. However, when I use `xprop`, it always outputs correct chars, so I am wondering how it is done ...

For now I am just trying to convert to UTF8 and if it fails, I convert it to UTF16, but I am wondering, if there is more idiomatic solution ...

UPD: it turns out, that WM_NAME can be also COUMPOUNT_TEXT ... I don't know if it is best, but I think that it makes sense to read it only as a STRING and if it is empty, than it is empty! ahhaa

I know that it is recommended to use _NET_WM_NAME instead, but I am curious, what's the right way to read WM_NAME property ...

**Comment by eduardosm** [comment]
`WM_NAME` can be of type `STRING` or `COMPOUND_TEXT`, but never `UTF8_STRING`. `_NET_WM_NAME` is always `UTF8_STRING`.

`STRING` is latin-1/8859-1 and `COMPOUND_TEXT` is some legacy [Frankenstein encoding](https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/CTEXT/ctext.html) that can embed multiple encodings.

Converting from/to latin-1 is easy. Converting from/to compound text... good luck.

`xprop` is probably doing the encoding conversion automatically for you, so it always shows the correct characters.

**Comment by andreykaere** [comment]
But why xprop shows, that most of the time WM_NAME is UTF8_STRING then?

**Comment by eduardosm** [comment]
Which application are you using `xprop` on? Can you post an output sample?

**Comment by psychon** [comment]
I tried it with `Chromium` and... yeah... well.... UTF8.
```
$ xprop WM_NAME   
WM_NAME(UTF8_STRING) = "WM_NAME: STRING vs UTF8_STRING · Issue #809 · psychon/x11rb - Chromium"
```
Looking at ICCCM, § 4.1.2. describes `WM_NAME`: https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.1

The above points to section 2.7.1 for the type atoms. This describes `STRING` as ISO Latin-1 and `COMPOUND_TEXT`. There is also `C_STRING` which I think I never read before...

Anyway, obviously ICCCM cannot mention UTF8 since ICCCM has copyright dates from 1987 to 1994 while the UTF-8 was apparently first presented in 1993. So... yeah...

Anyway, the only reason that `_NET_WM_NAME` exists is that it [must be encoded in UTF8](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm45317634134576). So I doubt whatever Chromium is doing here is entirely correct / spec compliant, but I also can understand why one would not want to use anything other than UTF8...

**Comment by andreykaere** [comment]
So the answer is if possible, read _NET_WM_NAME as UTF8_STRING. And if not, read WM_NAME as STRING?

**Comment by psychon** [comment]
Yeah, that should cover 99.9% of cases. But I don't know the correct answer that always works either. X11 is just X11...
