### ISSUE TITLE
Byte order of Image::get_from_reply()

### ISSUE THREAD

**Issue by 9ary** [psychon/x11rb#836]
I'm in the process of porting shotgun from xlib to x11rb: https://github.com/neXromancers/shotgun/pull/40.

I was digging in the code because some things were unclear from the documentation. One thing that caught my attention is that `Image::get_from_reply()` hardcodes big endian byte order:
https://github.com/psychon/x11rb/blob/5bd65b5a048fdb8474286a8f2aac5fd7a81fb8e1/x11rb/src/image.rs#L696-L712

However xlib gets this value from the connection setup: https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/208d550954c7266fa8093b02a2a97047e1478c00/src/ImUtil.c#L341

Is this a bug or is the byte order in GetImage responses actually supposed to always be big endian? The [spec](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:GetImage) doesn't say anything.

-----

Another thing I noticed is that format detection only considers depth and not bits_per_pixel:
https://github.com/psychon/x11rb/blob/5bd65b5a048fdb8474286a8f2aac5fd7a81fb8e1/x11rb/src/image.rs#L293-L300

Xlib seems to be the same thing in this case, but wouldn't this break for formats such as XRGB24, where the depth is 24 but pixels are padded to 32 bit words?
Edit: looking at 3 different xdpyinfo samples (an old machine, a modern one and my own machine with xwayland), it seems all the depths use a scanline_pad of 32 bits, and there's only one bits_per_pixel per depth value so there's that:
```
supported pixmap formats:
    depth 1, bits_per_pixel 1, scanline_pad 32
    depth 4, bits_per_pixel 8, scanline_pad 32
    depth 8, bits_per_pixel 8, scanline_pad 32
    depth 15, bits_per_pixel 16, scanline_pad 32
    depth 16, bits_per_pixel 16, scanline_pad 32
    depth 24, bits_per_pixel 32, scanline_pad 32
    depth 32, bits_per_pixel 32, scanline_pad 32
```

**Comment by psychon** [comment]
> One thing that caught my attention is that Image::get_from_reply() hardcodes big endian byte order:

Our image code is "heavily inspired" from xcb-image. That one also hardcodes big endian in `xcb_image_create_native`

https://gitlab.freedesktop.org/xorg/lib/libxcb-image/-/blob/525ce59fe2329d4b23fc0c52ed9dd92daac8ac2a/image/xcb_image.c#L188

However... this is not actually big endian. the `b` in `msb` means `bit`, not `byte`. See https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#server_response:

> bitmap-bit-order: { LeastSignificant, MostSignificant }

In other words... this is most likely completely insignificant since I would expect we will have a hard time finding an X11 server with a16 color displays. :-)

I didn't actually look at the Xlib code and there might still be more differences. This is just a quick, first reaction.

-----

> Another thing I noticed is that format detection only considers depth and not bits_per_pixel:

Uhm... isn't this list how we figure out which bits per pixel to use? In other words: Isn't this a `map<depth, (bits_per_pixel, scanline_pad>)`?

At least I think so, but I don't have much time to dig into things right now. Sorry. Quick code from the protocol reference manual (same link as above):

> Pixmap-formats contains one entry for each depth value. The entry describes the Z format used to represent images of that depth.

**Comment by 9ary** [comment]
> However... this is not actually big endian. the `b` in `msb` means `bit`, not `byte`. See https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#server_response:

It's a bit confusing then, since this is being passed to `Image::new()` as the byte_order argument. The documentation for ImageOrder also goes in that direction:
https://github.com/psychon/x11rb/blob/5bd65b5a048fdb8474286a8f2aac5fd7a81fb8e1/x11rb/src/image.rs#L462-L472

The setup info also has separate fields for byte order and pixmap bit order.
On my x86_64 machine, xdpyinfo says:
```
bitmap unit, bit order, padding:    32, LSBFirst, 32
image byte order:    LSBFirst
```
And indeed, decoding the pixel data as little endian seems to be correct.

> Uhm... isn't this list how we figure out which bits per pixel to use? In other words: Isn't this a `map<depth, (bits_per_pixel, scanline_pad>)`?

Looks like you're right. I was under the impression that the bits per pixel value was part of the response, but now that I look again that doesn't seem to be the case. Never mind then.

**Comment by psychon** [comment]
Okay, I am definitely confused.... so... would you say the following patch is right?
```diff
diff --git a/x11rb/src/image.rs b/x11rb/src/image.rs
index 0c55949..7317f54 100644
--- a/x11rb/src/image.rs
+++ b/x11rb/src/image.rs
@@ -706,7 +706,7 @@ impl<'a> Image<'a> {
             format.scanline_pad.try_into()?,
             reply.depth,
             format.bits_per_pixel.try_into()?,
-            ImageOrder::MsbFirst,
+            setup.image_byte_order.try_into()?,
             Cow::Owned(reply.data),
         )
     }
```

**Comment by 9ary** [comment]
Most likely yes, I ended up not using `x11rb::image` in my port since I already had well tested code to decode pixel data. I'm feeding `setup.image_byte_order` into it.
Also `Image::get()` is kind of useless currently since it discards the visual ID, and the whole image API lacks the ability to access the alpha channel (yes, the core protocol doesn't support it, but it works ¯\\\_(ツ)\_/¯). I'd love to contribute improvements for this but the port is already complete and that's a lot of effort for a tool I don't use (I daily wayland on all of my machines).

**Comment by psychon** [comment]
> Most likely yes

Works for me. Submitted as #837. Thanks for reporting this.

> since it discards the visual ID

Ahhh, nice catch. Since we are breaking API with the next release anyway: #837 changes the API so that this is now also returned.

> I'd love to contribute improvements for this but the port is already complete and that's a lot of effort for a tool I don't use (I daily wayland on all of my machines).

No problem. Thanks a lot for your report and your help already!

> Thanks a lot for writing x11rb regardless, it's pretty awesome other than the lack of documentation (which is not your fault).

Thanks. And welcome to X11. ;-) (Well, there is some documentation... but also there is not... it's all a bit weird and complicated. But I think you know what I mean.)

**Comment by 9ary** [comment]
> Thanks. And welcome to X11. ;-) (Well, there is some documentation... but also there is not... it's all a bit weird and complicated. But I think you know what I mean.)

Absolutely, the xlib docs are out there and mostly relevant at least, and as a last resort, reading its source code or the protocol spec gets you there. The specific lack of documentation I was referring to is just the same issue XCB suffers from: manpages exist for most functions but they are often functionally empty. At least rustdoc provides a good search feature and type information, which is great.
