### ISSUE TITLE
x11rb::image::Image::new byte order ignored?

### ISSUE THREAD

**Issue by daym** [psychon/x11rb#867]
Can it be that the byte order specified in `Image::new` is ignored by x11rb?

I specify it here https://github.com/daym/wmpanel/blob/dec21230cfb37b10b2ead6e0a8d0c8078fed554b/src/main.rs#L103 and then have to work around byte order here https://github.com/daym/wmpanel/blob/dec21230cfb37b10b2ead6e0a8d0c8078fed554b/src/main.rs#L321

I tried both MsbFirst and LsbFirst.

Or am I missing something?

P.S. If you want to try the thing, right now I'm doing the funny manual swapping only for non-svg icons.

**Comment by psychon** [comment]
Quick first reaction without having much time: I looked at callers of `new_x_image()` and found the code in `create_launcher()`. This calls `new_x_image()` (which is what calls `Image::new()`) and then calls `Image::put()` on the result.

Could you try whether replacing `image.put(...` with `image.native(conn.setup()).put(...` works?

Technical details: `new()` only saves the byte order, but doesn't do anything with it. Only `put_pixel()`, `get_pixel()` and `convert()` use the byte order. `convert()` can be used to convert an image to another byte order. And `native()` calls `convert()` with whatever the X11 server expects, i.e. converting to the server's byte order.

This API is modelled after what xcb-util-image does. That's not to say that this is a good thing. Dunno about that.

Some more quick thoughts:
- This could be considered a documentation issue and we'd have to improve the docs
- `put()` could check whether the image is in a format that the X11 server accepts (all of scanline pad, bits per pixel, and image byte order match a format supported by the server) and bail out if it doesn't. Dunno what "bail out" means exactly (panic? synthesise an error return?). The run-time overhead of such a check should likely be negligible.

**Comment by psychon** [comment]
I looked a bit at this and came up with the following:
```diff
diff --git a/Cargo.toml b/Cargo.toml
index aaa2ebf..3f1fc47 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -16,7 +16,7 @@ usvg = "0.35.0"
 which = "4.4.0"
 # TODO: features: cursor damage dpms image once_libloading cell randr render res resource_manager screensaver shape! shm sync! tracing xevie xinerama xfixes xf86vidmode xf86dri xinput xkb xprint xselinux xtest xv xvmc
 x11rb = { version = "0.12.0", features = ["image"] }
-xdgkit = { path = "../xdgkit" }
-# xdgkit = "3.2.3"
+#xdgkit = { path = "../xdgkit" }
+xdgkit = "3.2.3"
 
 #xcb = "1.2.1"
diff --git a/src/main.rs b/src/main.rs
index 7e916d7..8c91f6b 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -86,7 +86,45 @@ fn load_scale_image(
     ))
 }
 
+/// Check that the given visual is "as expected" (pixel values are 0xRRGGBB with RR/GG/BB being the
+/// colors). Otherwise, this exits the process.
+fn check_visual(screen: &Screen, id: Visualid) -> x11rb::image::PixelLayout {
+    // Find the information about the visual and at the same time check its depth.
+    let visual_info = screen
+        .allowed_depths
+        .iter()
+        .filter_map(|depth| {
+            let info = depth.visuals.iter().find(|depth| depth.visual_id == id);
+            info.map(|info| (depth.depth, info))
+        })
+        .next();
+    let (depth, visual_type) = match visual_info {
+        Some(info) => info,
+        None => {
+            eprintln!("Did not find the root visual's description?!");
+            std::process::exit(1);
+        }
+    };
+    // Check that the pixels have red/green/blue components that we can set directly.
+    match visual_type.class {
+        VisualClass::TRUE_COLOR | VisualClass::DIRECT_COLOR => {}
+        _ => {
+            eprintln!(
+                "The root visual is not true / direct color, but {:?}",
+                visual_type,
+            );
+            std::process::exit(1);
+        }
+    }
+    let result = x11rb::image::PixelLayout::from_visual_type(*visual_type)
+        .expect("The server sent a malformed visual type");
+    assert_eq!(result.depth(), depth);
+    result
+}
+
 fn new_x_image(
+    conn: &RustConnection,
+    screen: &Screen,
     image_width: u16,
     image_height: u16,
     image_data: &[u8],
@@ -104,6 +142,15 @@ fn new_x_image(
         Cow::Owned(image_data.to_vec()),
     )?;
 
+    // Convert the image from RGBx into the server's native format.
+    let data_layout = x11rb::image::PixelLayout::new(
+        x11rb::image::ColorComponent::new(8, 24)?,
+        x11rb::image::ColorComponent::new(8, 16)?,
+        x11rb::image::ColorComponent::new(8, 8)?,
+    );
+    let pixel_layout = check_visual(screen, screen.root_visual); // XXX Could move this out and look things up only once
+    let image = image.reencode(data_layout, pixel_layout, conn.setup())?;
+
     /*
     pub fn convert(
         &self,
@@ -114,7 +161,7 @@ fn new_x_image(
     */
 
     // TODO: scale or something. Maybe right after loading it from the file, tho?
-    Ok(image)
+    Ok(image.into_owned())
 }
 
 fn create_window(
@@ -312,6 +359,7 @@ fn create_launcher(
         let image_width = u16::try_from(local_image.width())?;
         let image_height = u16::try_from(local_image.height())?;
         let mut image_data = local_image.into_rgba8();
+        /*
         for (x, y, pixel) in image_data.enumerate_pixels_mut() {
             let image::Rgba(data) = *pixel;
             // apparently, x11rb wants [b, g, r, a] and we have [r, g, b, a].
@@ -324,12 +372,13 @@ fn create_launcher(
             // ^b  ^g ^r  ^ignored
             // *pixel = image::Rgba([data[1], data[2], data[3], data[0]]);
         }
+        */
 
-        new_x_image(image_width, image_height, &image_data)?
+        new_x_image(conn, screen, image_width, image_height, &image_data)?
     } else {
         if let Ok(image) = render_scale_image(icon_name, width.into(), height.into()) {
             let image_data = image.as_ref().data();
-            new_x_image(width, height, &image_data)?
+            new_x_image(conn, screen, width, height, &image_data)?
         } else {
             eprintln!("WTF");
             let mut image_data = Vec::<u8>::new();
@@ -338,7 +387,7 @@ fn create_launcher(
             for i in (0..size) {
                 image_data.push(0);
             }
-            new_x_image(width, height, &image_data)?
+            new_x_image(conn, screen, width, height, &image_data)?
         }
     };
     // TODO: image::imageops: blur, brighten, invert
@@ -409,7 +458,8 @@ fn read_lines(filename: &str) -> Vec<String> {
 }
 
 fn main() -> Result<(), Box<dyn std::error::Error>> {
-    let hidden_desktop_files = read_lines("/home/dannym/.fluxbox/guihidden");
+    //let hidden_desktop_files = read_lines("/home/dannym/.fluxbox/guihidden");
+    let hidden_desktop_files = vec![];
     let (conn, screen_num) = x11rb::connect(None).unwrap();
     let atoms = AtomCollection::new(&conn)?.reply()?;
     let screen = &conn.setup().roots[screen_num];
@@ -592,7 +642,10 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
                             working_directory,
                         );
                         match launcher {
-                            Ok(launcher) => launchers.push(launcher),
+                            Ok(launcher) => {
+                                launchers.push(launcher);
+                                break;
+                            }
                             Err(x) => {
                                 eprintln!("{:?}", x);
                             }
```
Half of that is just making things work for me locally (e.g. the changed dependency). The magic function `check_visual` is just a plain copy&paste from https://github.com/psychon/x11rb/blob/master/x11rb/examples/display_ppm.rs. I suggest to take a look at that example.

The important part is:
```rust
    let image = x11rb::image::Image::new(
        image_width,
        image_height,
        x11rb::image::ScanlinePad::Pad8,
        24, /* depth */
        x11rb::image::BitsPerPixel::B32,
        x11rb::image::ImageOrder::MsbFirst, // no effect
        Cow::Owned(image_data.to_vec()),
    )?;

    // Convert the image from RGBx into the server's native format.
    let data_layout = x11rb::image::PixelLayout::new(
        x11rb::image::ColorComponent::new(8, 24)?,
        x11rb::image::ColorComponent::new(8, 16)?,
        x11rb::image::ColorComponent::new(8, 8)?,
    );
    let pixel_layout = check_visual(screen, screen.root_visual); // XXX Could move this out and look things up only once
    let image = image.reencode(data_layout, pixel_layout, conn.setup())?;
```
This says that the input is "32 bits per pixel (`B32`)" with red in the first byte of such an element, etc (i.e. `0xRRGGBBXX` where `XX` is unused data). It then uses `reencode()` to translate that data to whatever the X11 server wants.

----

But to be honest, if you want to keep it simple, you most likely do not need the `Image` struct from x11rb. These days, basically all X11 servers expect the same kind of image data format.

You could just hardcode that format and hope for the best.

You could also check explicitly that the visual is class TrueColor and looks as expected. Basically the information from the following should be just like this (except for the visual id, of course):
```
$ xdpyinfo| grep -A 7 'default visual id: '
  default visual id:  0x21
  visual:
    visual id:    0x21
    class:    TrueColor
    depth:    24 planes
    available colormap entries:    256 per subfield
    red, green, blue masks:    0xff0000, 0xff00, 0xff
    significant bits in color specification:    8 bits
```
```
$ xdpyinfo| grep -A 7 'supported pixmap formats:' | grep 'depth 24'
    depth 24, bits_per_pixel 32, scanline_pad 32
```
This information could basically be checked in a similar way than my `check_visual()` function above, but instead of returning the result, it would just check that things look as expected. The pixmap format comes from `setup().pixmap_formats`.

Just hardcoding these assumptions and not supporting anything else could be a lot simpler than doing things "properly".

**Comment by daym** [comment]
> Could you try whether replacing `image.put(...` with `image.native(conn.setup()).put(...` works?

I tried it now. It's wrong in a different way then :)

I tried both MsbFirst and LsbFirst and then it does make a difference (both variants wrong).

> Technical details: `new()` only saves the byte order, but doesn't do anything with it. Only `put_pixel()`, `get_pixel()` and `convert()` use the byte order. `convert()` can be used to convert an image to another byte order. And `native()` calls `convert()` with whatever the X11 server expects, i.e. converting to the server's byte order.

I see!

> * `put()` could check whether the image is in a format that the X11 server accepts (all of scanline pad, bits per pixel, and image byte order match a format supported by the server) and bail out if it doesn't. Dunno what "bail out" means exactly (panic? synthesise an error return?). The run-time overhead of such a check should likely be negligible.

It's suprising to me that X11 doesn't do that on its own. What's all the info for if it doesn't check it? Weird. My first reaction to see X11's `Image` requiring all that metadata was "neat! Someone actually thought about checking all that stuff!". It turns out nope!

Not sure whether a binding should do this magic, though (even though it would be convenient). Probably only if there's no way the user could actually want the "wrong" settings to go through.

**Comment by daym** [comment]
Your big patch does work for me.

For xdpyinfo, I get:

```
  default visual id:  0x21
  visual:
    visual id:    0x21
    class:    TrueColor
    depth:    24 planes
    available colormap entries:    256 per subfield
    red, green, blue masks:    0xff0000, 0xff00, 0xff
    significant bits in color specification:    8 bits
```

**Comment by daym** [comment]
>Just hardcoding these assumptions and not supporting anything else could be a lot simpler than doing things "properly"

I see. I forgot all about the 8 bit color depth palette multiple planes days. That/'s probably what X is trying to support as well, right? 

I'm using a Rust image library already, so if that one can do it, I'd also like to try supporting weird formats as well (if only to serve as an example :) ).

Since this is a panel that I actually use for real, if an icon isn't supported, it shouldn't crash the entire panel (I have a fallback so it just puts a big empty box there instead--that you can still click). But if I understand you right, it would just exit at startup with the explicit test, right?

**Comment by psychon** [comment]
> I tried both MsbFirst and LsbFirst and then it does make a difference (both variants wrong).

Yeah, well, I guess one of them results in a color order of "xRGB" and the other one expects "BGRx", but neither matches the "RGBA" that the `image` crate gives you.

> It's suprising to me that X11 doesn't do that on its own. What's all the info for if it doesn't check it?

My mobile phone has more computing power than the systems that X11 was designed for. I think I once heared/read "fixing this up in the X11 server would be slow, so we provide all necessary information to the X11 client and let it deal with it".

And the `image` module in x11rb was designed after what xcb-util-image does and here... dunno. :shrug: 

> My first reaction to see X11's Image requiring all that metadata was "neat! Someone actually thought about checking all that stuff!". It turns out nope!

All the "stuff" that `Image` asks for is about how pixel values are stored. Nothing in there talks about "Is this RGB or BGR" (well, except for `reencode()` which gets two `PixelLayout` parameters for this stuff). So all of this complicated stuff is just for "stuff" where these days every sane system will just go "4 bytes per pixel" and then there is just the question of byte order. Sorry.

> For xdpyinfo, I get:

That looks quite sane and identical to what my system says. Dunno about big endian systems, but besides that, I expect every system to have a default visual like this.

> I see. I forgot all about the 8 bit color depth palette multiple planes days. That's probably what the X11 API is trying to support as well, right?

Kinda. X11 can still express way more stuff than what the `Image` API supports. Multiple planes ("first the first bit of each pixel, then the second pixel of each pixel") is just nuts. But `Image` itself just talks about "pixel value" without having any clue what a "pixel value" actually is. Only `Image::reencode()` and `PixelLayout` then make some assumptions about this.

> But if I understand you right, with the explicit test, it would just exit at startup, right?

My patch above should actually support quite a number of systems. The following should be dead code / unreachable / broken X11 server:
```rust
    let (depth, visual_type) = match visual_info {
        Some(info) => info,
        None => {
            eprintln!("Did not find the root visual's description?!");
            std::process::exit(1);
        }
    };
```
So that should leave this as the only possible error case:
```
    // Check that the pixels have red/green/blue components that we can set directly.
    match visual_type.class {
        VisualClass::TRUE_COLOR | VisualClass::DIRECT_COLOR => {}
        _ => {
            eprintln!(
                "The root visual is not true / direct color, but {:?}",
                visual_type,
            );
            std::process::exit(1);
        }
    }
```
If you want to know more about visual types, Google suggests https://tronche.com/gui/x/xlib/window/visual-types.html. Everything "Undecomposed Colormap" is about stuff like "16 colors where color 0 is white, 1 is black, 2 is red, ...". In these cases there is no pre-defined internal structure to color values. My patch above should accept TrueColor and DirectColor visuals which are "A pixel consists of individual R/G/B components". `PixelLayout` is then used to translate between different such decompositions.

So yeah, this would just exit when run against such an ancient X11 server. No idea how to even test this. Does Xorg still support something like this?

> P.S. It's awesome to have the right colors show up in the panel without very questionable loops that look like magic. Thank you!

No problem. The "a pixel is a u32 value in native endian and thus you end up with xBGR" always confuses everyone. :-)
