### ISSUE TITLE
How to monitor window for mouse motion?

### ISSUE THREAD

**Issue by markg85** [psychon/x11rb#927]
Hi,

I'm trying to monitor a window - Dolphin in this case - for mouse motion.

I don't receive any mouse motion with this code.
I also tried just monitoring the root window, same effect.
Am i missing something? Or did I just found a bug?

I added all the pointer masks that indicate some form of motion.

```rust
use x11rb::connection::Connection;
use x11rb::protocol::xproto::{AtomEnum, ChangeWindowAttributesAux, ConnectionExt as _, Window};
use x11rb::atom_manager;
use x11rb::protocol::xproto::*;
use x11rb::protocol::Event;

atom_manager! {
    pub AtomCollection: AtomCollectionCookie {
        WM_PROTOCOLS,
        WM_DELETE_WINDOW,
        _NET_WM_NAME,
        UTF8_STRING,
        _NET_SUPPORTING_WM_CHECK,
    }
}

fn find_windows(
    conn: &impl Connection,
    root: Window,
) -> Result<Vec<Window>, Box<dyn std::error::Error>> {
    let client_list = conn.intern_atom(false, b"_NET_CLIENT_LIST")?.reply()?.atom;
    let reply = conn
        .get_property(false, root, client_list, AtomEnum::WINDOW, 0, !0)?
        .reply()?;
    let windows = reply.value32().ok_or("Wrong property type")?.collect();
    Ok(windows)
}

fn get_window_string(
    conn: &impl Connection,
    window: Window,
) -> Result<String, Box<dyn std::error::Error>> {
    let atoms = AtomCollection::new(&conn)?.reply()?;

    let reply = conn
      .get_property(false, window, atoms._NET_WM_NAME, atoms.UTF8_STRING, 0, std::u32::MAX)?
      .reply()?;

    let title = String::from_utf8(reply.value)?;
    Ok(title)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (conn, screen_num) = x11rb::connect(None)?;
    let screen = &conn.setup().roots[screen_num];
    let mut window_to_monitor = 0;
    let windows = find_windows(&conn, screen.root)?;

    for window in windows {
        let title = get_window_string(&conn, window)?;
        println!("Window: {:?}, Title: {:?}", window, title);

        // if title contains Dolphin
        if title.contains("Dolphin") {
            window_to_monitor = window;
        }
    }

    let vau = ChangeWindowAttributesAux::default().event_mask(EventMask::EXPOSURE | EventMask::STRUCTURE_NOTIFY | EventMask::POINTER_MOTION | EventMask::BUTTON1_MOTION | EventMask::BUTTON2_MOTION | EventMask::BUTTON3_MOTION | EventMask::BUTTON4_MOTION | EventMask::BUTTON5_MOTION);
    conn.change_window_attributes(window_to_monitor, &vau)?;

    // Without this, the change_window_attributes() is not actually sent to the X11 server
    conn.flush()?;

    loop {
        let event = conn.wait_for_event()?;

        match event {
            Event::MotionNotify(event) => {
                println!("{:?}", event);
            }
            _ => {
                // Unknown event type, ignore it
                println!("Unknown event: {:?}", event);
            }
        }
    }
}
```

**Comment by notgull** [comment]
Try adding [`POINTER_MOTION`](https://docs.rs/x11rb/latest/x11rb/protocol/xproto/struct.EventMask.html#associatedconstant.POINTER_MOTION) to the flags.

**Comment by psychon** [comment]
Welcome to X11 where input event handling is complicated. ;-)

I took your program and just run it without any running Dolphins. It printed the window IDs of the existing windows. `xterm` showed up as
```
Window: 46137358, Title: ""
```
I added this to the program as
```rust
    let mut window_to_monitor = 46137358;
```
Running the resulting program again worked fine. But I didn't enable the `extra-traits` feature. One rebuild and rerun later, I get:
```
MotionNotifyEvent { response_type: 6, detail: NORMAL, sequence: 45, time: 13367780, root: 1497, event: 46137358, child: 46137370, root_x: 1896, root_y: 486, event_x: 1895, event_y: 448, state: 0, same_screen: true }
MotionNotifyEvent { response_type: 6, detail: NORMAL, sequence: 45, time: 13367781, root: 1497, event: 46137358, child: 46137370, root_x: 1750, root_y: 504, event_x: 1749, event_y: 466, state: 0, same_screen: true }
MotionNotifyEvent { response_type: 6, detail: NORMAL, sequence: 45, time: 13367789, root: 1497, event: 46137358, child: 46137370, root_x: 1680, root_y: 514, event_x: 1679, event_y: 476, state: 0, same_screen: true }
```
So, your program works fine. X11 just does not work the way you expect it to work.

https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#events:MotionNotify

> The event window is found by starting with the source window and looking up the hierarchy for the first window on which any client has selected interest in the event 

So, you asked for these events on Dolphin's top level window. But apparently Dolphin creates other windows as children of this window and asked for pointer events for these windows. Since these windows already "get" the window, windows further up the window hierarchy do not get the window any more.

> I also tried just monitoring the root window, same effect.

That should work if you move your mouse cursor across the wallpaper, i.e. not inside of any window.

Welcome to X11. :disappointed:

**Comment by markg85** [comment]
Hi @psychon 

Thank you for your elaborate response! That's much appreciated :)
But even with that help i still can't get these events to show up.

You mentioned `But I didn't enable the extra-traits feature`, i don't have any features enabled. Are there specific features i need to enable for this to work?

**Comment by psychon** [comment]
> Are there specific features i need to enable for this to work?

Ah, sorry. Without the `extra-traits` feature, the `Debug` impl for "things" do not actually print the contents, so you get less helpful output. But that doesn't make any difference with whether you get output.

> I tried all their IDs but none worked. Except xterm!

It also works for me with urxvt. :-) 

GVim does not work. And according to `xwininfo -tree`, it does not have any (relevant) child windows. So this cannot be the reason...

Looking at this with `xtrace`... uhm... `SelectEvents` feels like something sensible to look for:
```
$ grep SelectEvents /tmp/t
000:<:0071: 20: XInputExtension-Request(131,46): XISelectEvents win=0x000005d9 masks={device=0 mask=0x00001802;};
000:<:007d: 24: XInputExtension-Request(131,46): XISelectEvents win=0x03200001 masks={device=1 mask=0xf81c01f0,0x00000001;};
000:<:008d: 16: XKEYBOARD-Request(135,1): SelectEvents opcode=0x87 opcode2=0x01 unparsed-data=0x00,0x01,0x07,0x00,0x00,0x00,0x07,0x00,0xff,0x00,0xff,0x00;
000:<:008e: 20: XKEYBOARD-Request(135,1): SelectEvents opcode=0x87 opcode2=0x01 unparsed-data=0x00,0x01,0x04,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0x3f,0x11,0x00;
000:<:00aa: 24: XInputExtension-Request(131,46): XISelectEvents win=0x03200004 masks={device=1 mask=0x0000060c,0x00000000;};
000:<:00bc: 24: XInputExtension-Request(131,46): XISelectEvents win=0x03200003 masks={device=1 mask=0xf81c07fc,0x00000001;};
000:<:00fb: 24: XInputExtension-Request(131,46): XISelectEvents win=0x03200003 masks={device=1 mask=0xf81c07fc,0x00000001;};
000:<:0146: 24: XInputExtension-Request(131,46): XISelectEvents win=0x03200003 masks={device=1 mask=0xf81c07fc,0x00000001;};
000:<:02eb: 20: XKEYBOARD-Request(135,1): SelectEvents opcode=0x87 opcode2=0x01 unparsed-data=0x03,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x05,0x00,0x05,0x00;
000:<:02ec: 16: XKEYBOARD-Request(135,1): SelectEvents opcode=0x87 opcode2=0x01 unparsed-data=0x03,0x00,0x02,0x00,0x00,0x00,0x00,0x00,0x07,0x00,0x07,0x00;
```
Since this is not about keyboards, I am going to ignore that. Instead, I'll assume that this is about XInput. Google suggests https://www.x.org/releases/X11R7.7/doc/inputproto/XI2proto.txt But I cannot find anything in there about its interaction with core events. Perhaps no core event is generated if "anything" requested XI input events?

-------

Let's take a step back here: @markg85 

> I'm trying to monitor a window - Dolphin in this case - for mouse motion.

What exactly does this mean? You want to know whenever the mouse cursor moves, but only while inside the `Dolphin` window? Is it a hard requirement not to get "more than that"?

We could ignore the "while inside `Dolphin`" part. With a [GrabPointer](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:GrabPointer) request with `pointer-mode` set to `Asynchronous`, you can get a grab that allows you to have the events still sent to dolphin. Whenever you get an input event, you send an [AllowEvents](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:AllowEvents) request to have the input replayed, but this time ignoring the grab.

Perhaps this is a better approach? And hopefully the above-linked docs can help you in figuring out the details.

**Comment by markg85** [comment]
> What exactly does this mean? You want to know whenever the mouse cursor moves, but only while inside the Dolphin window? Is it a hard requirement not to get "more than that"?

Dolphin was easier to explain then to actually explain it ;)

What i want to make is desktop streaming (super short detail, i want to use libx264rgb which looks superior to anything else at the cost of more bandwidth). I've got the streaming portion working just fine, just `simple` ffmpeg commands. Now i still need to get the keyboard and mouse events over the wire. For that i need to capture all events happening in 1 window (the window in which the stream is displayed). Sending these events from the "receiver" (the monitor displaying the stream) and "sender" (the pc which framebuffer is captured) will be done using sockets.

I don't quite care how i get these events from the "receiver" as long as i get them all to send them to the "sender". Do you think that this usecase should use GrabPointer instead?

**Comment by psychon** [comment]
https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:ChangeWindowAttributes

> [...]
> However, only one client at a time can select for SubstructureRedirect, only one client at a time can select for ResizeRedirect, and only one client at a time can select for [ButtonPress](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#events:ButtonPress). An attempt to violate these restrictions results in an Access error.

"Something else" (whoever that might be) already selected ButtonPress on the window. X11 does not provide a mechanism to figure out which other client selected events.
